version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.16
    - 8.0.17
    - 8.0.18
    - 8.1.0
    - 9.0.0
    - 9.1.0
  - dependency-name: "@sudoo/triforce"
    versions:
    - 2.9.13
    - 2.9.14
    - 2.9.15
    - 2.9.16
    - 2.9.17
    - 2.9.18
    - 2.9.20
    - 2.9.21
    - 2.9.22
  - dependency-name: license-webpack-plugin
    versions:
    - 2.3.11
    - 2.3.12
    - 2.3.14
    - 2.3.15
    - 2.3.16
  - dependency-name: "@types/copy-webpack-plugin"
    versions:
    - 6.4.1
  - dependency-name: "@types/webpack-bundle-analyzer"
    versions:
    - 3.9.1
    - 3.9.2
  - dependency-name: "@types/webpack"
    versions:
    - 5.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
